[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hook-caller"
version = "0.1.0"
description = "Web hook job tracker hook caller"
requires-python = ">=3.9"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[project.optional-dependencies]
local = ["shared @ file://localhost/${PROJECT_ROOT}/../shared"]
