services:
  repo-checker:
    build:
      context: ..
      dockerfile: repo-checker/Dockerfile
    container_name: repo-checker
    env_file:
      - ./.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always
    networks:
      - dev-shared

networks:
  dev-shared:
    external: true
    name: web-hook-job-tracker-dev-shared
