services:
  webhook-publisher:
    build:
      context: ..
      dockerfile: webhook-publisher/Dockerfile
    container_name: webhook-publisher
    env_file:
      - ./.env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_DSN_URL: postgresql://myUser:mySecretPassword@db:5432/webhook_db
    restart: always
    networks:
      - dev-shared

networks:
  dev-shared:
    external: true
    name: web-hook-job-tracker-dev-shared
