version: "3"

services:
  db:
    image: postgres:17-alpine
    volumes:
      - dev-main-db:/var/lib/postgresql/data
      - ./sql/dev_init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: mySecretPassword
      POSTGRES_USER: myUser
      POSTGRES_DB: myDb
    ports:
      - "5432:5432"

volumes:
  dev-main-db:
